services:
  web:
    build: ./site
    volumes:
      -journals-data:/app/templates/journals:ro
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PLAUSIBLE_SRC_URL=  # Optional
      - PLAUSIBLE_DATA_API=  # Optional
      - PLAUSIBLE_DATA_DOMAIN=  # Optional
      - GITHUB_USERNAME=  # Optional
  collector:
    build: ./collector
    volumes:
      -journals-data:/app/data
    restart: unless-stopped
    environment:
      - GITHUB_USERNAME=  # Required
      - GITHUB_TOKEN=  # Required
volumes:
  journals-data:
